services:
    wrench-serv:
        image: ryukzak/wrench
        environment:
            - PORT=8080
            - WRENCH_EXEC=wrench
            - STORAGE_PATH=/data
        ports:
            - "8080:8080"
        volumes:
            - ./uploads:/data
