services:
  wrench-serv:
    image: wrench
    environment:
      - PORT=8080
      - WRENCH_EXEC=wrench
      - STORAGE_PATH=/data
      - VARIANTS=/variants
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/data
